name: "MatterBridge Virtual Utilization v2"
packageKey: matter-bridge-virtual-utilization
description: "MatterBridge Virtual Binary Sensor mapped to Appliance Utilization"
permissions:
  matter: {}
vendorSupportInformation: "https://github.com/weber"
